apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: jordanmeyer
spec:
  selector:
    app: redis
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379