apiVersion: v1
kind: Service
metadata:
  name: lab5
  labels:
    app: lab5
  namespace: jordanmeyer
spec:
  type: ClusterIP
  selector:
    app: lab5
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000